---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:1.21.*
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/martenhellqvist/flux-get-started-2.git
    ref: master
    path: charts/ghost
  values:
    image: bitnami/ghost:3.2.0-debian-9-r16
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 100m
    serviceType: ClusterIP
    mariadb:
      persistence:
        enabled: false
