---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    fluxcd.io/automated: true     
    fluxcd.io/tag.chart-image: glob:master-*
spec:
  releaseName: mongodb
  chart:
    git: ssh://git@github.com:helm/charts.git
    path: stable/mongodb
    ref: master
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.14
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
